apiVersion: autoscaling/v2  
kind: HorizontalPodAutoscaler  
metadata:
  name: hbolajraf-webapp-hpa  # Name of the HPA resource
spec:
  scaleTargetRef: 
    apiVersion: apps/v1 
    kind: Deployment  
    name: hbolajraf-webapp  # Name of the Deployment to scale
  minReplicas: 1  # Minimum number of pods to maintain even during low traffic
  maxReplicas: 5  # Maximum number of pods to scale up during high traffic
  metrics:  # Define resource-based scaling metrics
  - type: Resource  
    resource:
      name: cpu  # Scale based on CPU usage
      target:
        type: Utilization  # Use utilization percentage as the target metric
        averageUtilization: 70  # Trigger scaling when average CPU utilization exceeds 70%
  - type: Resource  
    resource:
      name: memory  # Scale based on memory usage
      target:
        type: Utilization  # Use utilization percentage as the target metric
        averageUtilization: 70  # Trigger scaling when average memory utilization exceeds 70%
  behavior: 
    scaleDown:  # Rules for scaling down (reducing pods)
      stabilizationWindowSeconds: 60   # Wait 60 seconds before applying scale-down
      policies:
      - type: Pods
        value: 1  # Reduce the number of pods by a maximum of 1 pod at a time
        periodSeconds: 60  # Allow scale-down operations every 60 seconds
      - type: Percent
        value: 40  # Reduce the number of pods by a maximum of 40% of total pods at a time
        periodSeconds: 60  # Allow scale-down operations every 60 seconds
